using System.Text;
using Microsoft.CodeAnalysis;

namespace osu.Game.Rulesets.O2Lazer.SourceGeneration;

[Generator]
public class O2LazerColumnSourceGenerator : ISourceGenerator
{
    private const int max_columns = 18;

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        context.AddSource("O2LazerColumnProvider.g.cs", generateProvider());
        context.AddSource("O2LazerColumnFactory.g.cs", generateFactory());
    }

    private static string generateProvider()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace osu.Game.Rulesets.O2Lazer.Objects;");
        sb.AppendLine();
        sb.AppendLine("public interface IColumnProvider { int Value { get; } }");
        for (var i = 0; i < max_columns; i++)
        {
            sb.AppendLine($"public readonly struct Column{i} : IColumnProvider {{ public int Value => {i}; }}");
        }

        return sb.ToString();
    }

    private static string generateFactory()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using osu.Game.Rulesets.O2Lazer.Objects;");
        sb.AppendLine();
        sb.AppendLine("namespace osu.Game.Rulesets.O2Lazer.UI.Components;");
        sb.AppendLine();
        sb.AppendLine("public static class O2LazerColumnFactory");
        sb.AppendLine("{");
        sb.AppendLine("    public static Type GetColumnProviderType(int index) => index switch");
        sb.AppendLine("    {");
        for (var i = 0; i < max_columns; i++)
            sb.AppendLine($"        {i} => typeof(Column{i}),");
        sb.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(index)),");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
